# Generated by Django 3.0 on 2023-03-17 10:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('oc_lettings_site', '0002_auto_20230317_1113'),
        ('lettings', '0002_auto_20230317_1113'),
        ('profiles', '0002_auto_20230317_1136'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
